# Generated by Django 4.2.5 on 2023-09-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_randomdemo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomDemo',
        ),
    ]
