# Generated by Django 4.2.5 on 2023-09-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_delete_randomdemo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursecode',
            field=models.CharField(max_length=20, unique='true'),
        ),
    ]
